### ISSUE TITLE
Authentication related tests are failing

### ISSUE THREAD

**Issue by horacio** [ombulabs/mercadopago#18]
Hi,

Just ran the test suite and the following cases failed:

- `test_that_authentication_fails_with_wrong_parameters`
- `test_that_request_fails_with_wrong_token`
- `test_that_refresh_token_works`

It seems that the MercadoPago API error handling has changed. For example, on the access token refresh test, the API now responds with a 400, saying that the user "has not grant for application" (which is kind of weird).

Should I update the tests to reflect these new error responses?

Thanks.

**Comment by j0sephandres1987** [comment]
I'm just newbie rails developer, run tests It is very difficult for me and this is only an application to learn ruby on rails framework,  i have used another gems to integrate mercadopago and any works for me not even the official

**Comment by j0sephandres1987** [comment]
by the way, i just tried with PHP the official gem-sdk AND IT WORKS PERFECTLY

**Comment by etagwerker** [comment]
@horacio We just added `vcr` to make sure that these tests work without depending on the Mercado Pago server. 

Thanks!
