### ISSUE TITLE
Problems with authentication?

### ISSUE THREAD

**Issue by fzuppa** [ombulabs/mercadopago#37]
I haven't been able to log in for the last couple of days.
It seems the problem is that [refresh_token is taken as mandatory](https://github.com/ombulabs/mercadopago/blob/ac8845dec29c16220102dd517ffc7ed3b259381b/lib/mercadopago/client.rb#L194), but oauth is not returning it (copied the responde below). 

Are you aware of the problem? Planning to solve it?

`{"access_token":"XXXX","live_mode":true,"user_id":xxxxx,"token_type":"bearer","expires_in":21600,"scope":"offline_access payments read write"}%  `

**Comment by etagwerker** [comment]
Just merged the commit by @Miguelcldn. Please test again using `master`. It should work.

**Comment by federicozuppa** [comment]
Works perfect. Thanks a log guys

**Comment by Miguelcldn** [comment]
Hey guys, I just created a PR removing the temporal comment about the `refresh_token` issue. I you want we can discuss there what to do next. Mercadolibre told me it was due a bug in their API and it's now fixed, but in my opinion `refresh_token` is not *that* required.
